### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by exatn** [exasol/spark-connector#143]
This link in the User Guide to the repo on Maven is broken.  
`You can find all the releases at [com.exasol/spark-connector](https://central.sonatype.com/search?q=%2522spark-connector_2.13%2522%2520%2522com.exasol%2522) page.
`
I think this URL would be better: 
`https://central.sonatype.com/artifact/com.exasol/spark-connector_2.13/1.3.0-spark-3.3.2/versions`

**Comment by morazow** [comment]
Thanks @exatn,
Yes, I remember previously it showed only Exasol artifact. Your suggestion is only for one version, but still may be good idea, since users can then choose the latest one from the upper right corner.
