### ISSUE TITLE
Spark Connector is not compatible with exasol-jdbc V24+ anymore

### ISSUE THREAD

**Issue by hunnguye** [exasol/spark-connector#227]
Dear Maintainer and Contributors,

Thank you for your time and effort.

Using the following Versions:
* exasol-jdbc : 24.1.1
* spark-connector: 2.6.1

And running a simple df.write.

The following error occurs:
`java.sql.SQLException: [ERROR] Connection String does not support (workerID) argument.`

This is likely because the connection string constructed includes an argument called workerid 
https://github.com/exasol/spark-connector/blob/c83d655e9f98a873c1cd23474d1be2307f171965/exasol-jdbc/src/main/scala/com/exasol/spark/util/ExasolConnectionManager.scala#L85

However the exasol jdbc driver had a change in V24, which now validates the arguments of the connection string (https://exasol.my.site.com/s/article/Changelog-content-18389?language=en_US). The jdbc driver does not support an argument called workerid (https://docs.exasol.com/db/7.1/connect_exasol/drivers/jdbc.htm#IntegrateJDBCDriverusingMaven).

Since I've noticed, there is not much documentation on the internet and the change is quite recently I created this issue to bring it to your attention.

Thank you and best regards

**Comment by kaklakariada** [comment]
Hi @hunnguye,
thanks for your bug report and very detailed analysis! We will fix this soon.

**Comment by Shmuma** [comment]
Looks like `workerID` was renamed into `comment` argument (https://github.com/exasol/drivers/commit/dee3af0a4a2ce4db62ae2fecf91e72d96d406485). 
Strange naming, need to check deeper when and why it happened
