### ISSUE TITLE
Enable dataframe.show() for cluster environment

### ISSUE THREAD

**Issue by 3cham** [exasol/spark-connector#27]
User may run dataframe.show() to have a glance at the underlying data. It is only 1 task job:
```
INFO DAGScheduler: Submitting 1 missing tasks from ResultStage
```
So in the test environment (only 1 node exasol cluster) it runs completely fine. However, if it runs in cluster environment, will cause the known connection error because it is mandatory that all the nodes receive the same query. 

The idea to solve this problem is introduce a lazy metadata object inside ExasolRelation, which caches (only after called) the information of first 20 rows (It is not really necessary to have more), maybe also number of rows and so on. It could be done by calling just one normal jdbc call.

**Comment by redcatbear** [comment]
Closing because not in roadmap focus.
